//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (matching controller-gen output). DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CloudflareSpec) DeepCopyInto(out *CloudflareSpec) {
	*out = *in
	out.APITokenSecretRef = in.APITokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CloudflareSpec) DeepCopy() *CloudflareSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DCInstanceSpec) DeepCopyInto(out *DCInstanceSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DCInstanceSpec) DeepCopy() *DCInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DCInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DCInstanceStatus) DeepCopyInto(out *DCInstanceStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.SecondsBehindSource != nil {
		in, out := &in.SecondsBehindSource, &out.SecondsBehindSource
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DCInstanceStatus) DeepCopy() *DCInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DCInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *IssuerRef) DeepCopyInto(out *IssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *IssuerRef) DeepCopy() *IssuerRef {
	if in == nil {
		return nil
	}
	out := new(IssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MysqlReplicaPair) DeepCopyInto(out *MysqlReplicaPair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MysqlReplicaPair) DeepCopy() *MysqlReplicaPair {
	if in == nil {
		return nil
	}
	out := new(MysqlReplicaPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *MysqlReplicaPair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MysqlReplicaPairList) DeepCopyInto(out *MysqlReplicaPairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MysqlReplicaPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MysqlReplicaPairList) DeepCopy() *MysqlReplicaPairList {
	if in == nil {
		return nil
	}
	out := new(MysqlReplicaPairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *MysqlReplicaPairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MysqlReplicaPairSpec) DeepCopyInto(out *MysqlReplicaPairSpec) {
	*out = *in
	in.DC1.DeepCopyInto(&out.DC1)
	in.DC2.DeepCopyInto(&out.DC2)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FailoverCooldown != nil {
		in, out := &in.FailoverCooldown, &out.FailoverCooldown
		*out = new(metav1.Duration)
		**out = **in
	}
	in.Sidecar.DeepCopyInto(&out.Sidecar)
	if in.MysqlConf != nil {
		in, out := &in.MysqlConf, &out.MysqlConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MysqlReplicaPairSpec) DeepCopy() *MysqlReplicaPairSpec {
	if in == nil {
		return nil
	}
	out := new(MysqlReplicaPairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MysqlReplicaPairStatus) DeepCopyInto(out *MysqlReplicaPairStatus) {
	*out = *in
	in.DC1.DeepCopyInto(&out.DC1)
	in.DC2.DeepCopyInto(&out.DC2)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastFailover != nil {
		in, out := &in.LastFailover, &out.LastFailover
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MysqlReplicaPairStatus) DeepCopy() *MysqlReplicaPairStatus {
	if in == nil {
		return nil
	}
	out := new(MysqlReplicaPairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SidecarSpec) DeepCopyInto(out *SidecarSpec) {
	*out = *in
	if in.LeaseTimeout != nil {
		in, out := &in.LeaseTimeout, &out.LeaseTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PeerCheckInterval != nil {
		in, out := &in.PeerCheckInterval, &out.PeerCheckInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SidecarSpec) DeepCopy() *SidecarSpec {
	if in == nil {
		return nil
	}
	out := new(SidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	out.IssuerRef = in.IssuerRef
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
