apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bloodraven
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/shipstream/bloodraven/gh-pages
    chart: bloodraven
    targetRevision: 1.0.0
    helm:
      values: |
        metrics:
          service:
            enabled: true
          serviceMonitor:
            enabled: true
        grafanaDashboards:
          enabled: true
          namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: bloodraven
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
