image:
  repository: ghcr.io/shipstream/bloodraven
  tag: "0.9.0"
  pullPolicy: IfNotPresent

replicaCount: 1

leaderElection:
  enabled: true

metrics:
  service:
    enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: kube-prometheus-stack

grafanaDashboards:
  enabled: true
  namespace: monitoring
  folder: Bloodraven

auxiliary:
  service:
    enabled: false
    wsAllowedOrigins: "https://dashboard.example.com"
